[workspace]
members = ["cli", "gui", "lang-derive", "lang-core"]
resolver = "3"
default-members = ["gui"]

[workspace.package]
edition = "2024"
version = "0.1.1"
license = "Apache-2.0"

[workspace.dependencies]
# Common dependencies
smol = "2.0.2"
sha3 = "0.10.8"
num_cpus = "1.17.0"
futures = "0.3.31"
sysinfo = { version = "0.37.0", default-features = false, features = ["disk"] }
regex = "1.11.2"
once_cell = "1.20.0"

# BMS
bms-rs = "0.9.0" 
encoding_rs = "0.8.35"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"

# Zip
zip = "5.1.1"
sevenz-rust = "0.6.1"
unrar = "0.5.8"

# FS
which = "8.0.0"
strsim = "0.11.1"
xlsxwriter = "0.6.1"

# GUI
clap = { version = "4.4", features = ["derive"] }
iced = { version = "0.13", features = ["smol", "multi-window"] }
blocking = "1"
syn = { version = "2", features = ["full", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
fontdb = "0.23.0"
ttf-parser = "0.25.1"
unicode-segmentation = "1.12.0"
unicode-width = "0.2.1"
rfd = "0.15.4"

# Logging
log = "0.4"
env_logger = "0.11"

# Tempfile
tempfile = "3.20.0"