[package]
name = "lang-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "visit"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
lang-core = { path = "../lang-core" }

